<?php
namespace Mexbs\Tieredcoupon\Helper;

class Data extends \Magento\Framework\App\Helper\AbstractHelper
{
    protected $tieredCouponFactory;
    protected $autogeneratedTieredCouponCodeFactory;

    public function __construct(
        \Mexbs\Tieredcoupon\Model\TieredcouponFactory $tieredCouponFactory,
        \Mexbs\Tieredcoupon\Model\AutogeneratedFactory $autogeneratedTieredCouponCodeFactory,
        \Magento\Framework\App\Helper\Context $context
    )
    {
        $this->tieredCouponFactory = $tieredCouponFactory;
        $this->autogeneratedTieredCouponCodeFactory = $autogeneratedTieredCouponCodeFactory;
        parent::__construct($context);
    }


    public function getTieredCouponByCouponCode($couponCode){
        /**
         * @var \Mexbs\Tieredcoupon\Model\Tieredcoupon $tieredCoupon
         */
        $tieredCoupon = $this->tieredCouponFactory->create();
        $tieredCoupon->load($couponCode, 'code');
        if($tieredCoupon->getId()){
            return $tieredCoupon;
        }

        /**
         * @var \Mexbs\Tieredcoupon\Model\Autogenerated $autogeneratedTieredCouponCode
         */
        $autogeneratedTieredCouponCode = $this->autogeneratedTieredCouponCodeFactory->create();
        $autogeneratedTieredCouponCode->load($couponCode, 'code');
        if($autogeneratedTieredCouponCode->getId()){
            $tieredCouponId = $autogeneratedTieredCouponCode->getTieredcouponId();
            if($tieredCouponId){
                $tieredCoupon = $this->tieredCouponFactory->create();
                $tieredCoupon->load($tieredCouponId);
                if($tieredCoupon->getCode()){
                    return $tieredCoupon;
                }
            }
        }

        return null;
    }
}