<!-- TODO - THIS WILL NEED STYLING, ETC... -->

<?php $shipmentItems = $block->getShipmentItems();?>
<?php foreach($shipmentItems as $shipmentItem){?>
<?php 
    //The item is already the bundle item
    $item = $shipmentItem['item'];
    $qty = $shipmentItem['qty'];
    $product = $item->getProduct();
    $baseImageUrl = 'https://molekule.com/go/media/catalog/product' . $product->getData('image');
    ?>
<table align="center" class="container float-center" style="Margin:0 auto;background:#fff;border-collapse:collapse;border-spacing:0;float:none;margin:0 auto;padding:0;text-align:center;vertical-align:top;width:600px">
    <tbody>
    <tr style="padding:0;text-align:left;vertical-align:top">
        <td bgcolor="white" style="-moz-hyphens:none;-webkit-hyphens:none;Margin:0;border-collapse:collapse!important;color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:lighter;hyphens:none;line-height:1.3;margin:0;padding:0 20px;background-color:white;text-align:left;vertical-align:top;word-break:normal!important">
            <table class="wrapper" align="center" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                <tbody>
                <tr style="padding:0;text-align:left;vertical-align:top">
                    <td class="wrapper-inner" style="-moz-hyphens:none;-webkit-hyphens:none;Margin:0;border-collapse:collapse!important;color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:lighter;hyphens:none;line-height:1.3;margin:0;padding:0;text-align:left;vertical-align:top;word-break:normal!important">
                        <table class="row" style="border-collapse:collapse;border-spacing:0;display:table;padding:0;position:relative;text-align:left;vertical-align:top;width:100%">
                            <tbody>
                            <tr style="padding:0;text-align:left;vertical-align:top">
                                <th class="small-12 large-6 columns first" style="Margin:0 auto;color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:lighter;line-height:1.3;margin:0 auto;padding:0;padding-bottom:0;padding-left:0px;padding-right:10px;text-align:left;vertical-align:middle;width:260px" valign="middle">
                                    <table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                                        <tbody>
                                        <tr style="padding:0;text-align:left;vertical-align:top">
                                            <th style="Margin:0;color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:lighter;line-height:1.3;margin:0;padding:0;text-align:left">
                                                <table class="spacer" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                                                    <tbody>
                                                    <tr style="padding:0;text-align:left;vertical-align:top">
                                                        <td height="10px" style="-moz-hyphens:none;-webkit-hyphens:none;Margin:0;border-collapse:collapse!important;color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:10px;font-weight:lighter;hyphens:none;line-height:10px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-break:normal!important"></td>
                                                    </tr>
                                                    </tbody>
                                                </table>

                                                <center data-parsed="" style="min-width:240px;width:100%">
                                                    <div ap:edit="" align="center" class="float-center"><a style="-moz-hyphens:none!important;-ms-hyphens:none!important;-webkit-hyphens:none!important;hyphens:none!important;white-space:no-wrap!important;word-break:keep-all!important;word-wrap:normal!important; color:#000000!important; display: block;width:100%;text-align:center;" href="http://molekule.com/"><img alt="<?= $block->escapeHtml($item->getName()) ?>" style="-ms-interpolation-mode:bicubic;clear:both;display:block;max-width:100%;outline:0;text-decoration:none;width:auto; margin:0 auto;" src="<?= $baseImageUrl; ?>" /></a></div>
                                                </center>

                                                <table class="spacer show-for-large" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                                                    <tbody>
                                                    <tr style="padding:0;text-align:left;vertical-align:top">
                                                        <td height="10px" style="-moz-hyphens:none;-webkit-hyphens:none;Margin:0;border-collapse:collapse!important;color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:10px;font-weight:lighter;hyphens:none;line-height:10px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-break:normal!important"></td>
                                                    </tr>
                                                    </tbody>
                                                </table>
                                            </th>
                                        </tr>
                                        </tbody>
                                    </table>
                                </th>
                                <th class="small-12 large-6 columns last" style="Margin:0 auto;color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:lighter;line-height:1.3;margin:0 auto;padding:0;padding-bottom:0;padding-left:10px;padding-right:0px;text-align:left;vertical-align:middle;width:260px" valign="middle">
                                    <table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                                        <tbody>
                                        <tr style="padding:0;text-align:left;vertical-align:top">
                                            <th style="Margin:0;color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:lighter;line-height:1.3;margin:0;padding:0;text-align:left">
                                                <table class="spacer show-for-large" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                                                    <tbody>
                                                    <tr style="padding:0;text-align:left;vertical-align:top">
                                                        <td height="25px" style="-moz-hyphens:none;-webkit-hyphens:none;Margin:0;border-collapse:collapse!important;color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:25px;font-weight:lighter;hyphens:none;line-height:25px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-break:normal!important"></td>
                                                    </tr>
                                                    </tbody>
                                                </table>

                                                <div ap:edit="">
                                                    <p class="small-text-center toofus" style="-moz-hyphens:none!important;-ms-hyphens:none!important;-webkit-hyphens:none!important;Margin:0;Margin-bottom:0;border-collapse:collapse!important;color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:lighter;hyphens:none!important;line-height:1.45;margin:0;margin-bottom:0;padding:0;text-align:left;white-space:no-wrap!important;word-break:keep-all!important;word-wrap:normal!important"><strong style="-moz-hyphens:none!important;-ms-hyphens:none!important;-webkit-hyphens:none!important;hyphens:none!important;white-space:no-wrap!important;word-break:keep-all!important;word-wrap:normal!important"><?php echo $item->getName(); ?></strong></p>
                                                </div>

                                                <div ap:edit="">
                                                    <p class="small-text-center" style="-moz-hyphens:none!important;-ms-hyphens:none!important;-webkit-hyphens:none!important;Margin:0;Margin-bottom:0;border-collapse:collapse!important;color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:300;hyphens:none!important;line-height:1.45;margin:0;margin-bottom:0;padding:0;text-align:left;white-space:no-wrap!important;word-break:keep-all!important;word-wrap:normal!important">
                                                    <?= strip_tags($product->getShortDescription()) ?></p>
                                                </div>

                                                <div ap:edit="">
                                                    <p class="small-text-center" style="-moz-hyphens:none!important;-ms-hyphens:none!important;-webkit-hyphens:none!important;Margin:0;Margin-bottom:0;border-collapse:collapse!important;color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:300;hyphens:none!important;line-height:1.45;margin:0;margin-bottom:0;padding:0;text-align:left;white-space:no-wrap!important;word-break:keep-all!important;word-wrap:normal!important">Serial number:</p>
                                                    <?php foreach($shipmentItem['serialNumbers'] as $serialNumber){?>
                                                        <p class="small-text-center" style="-moz-hyphens:none!important;-ms-hyphens:none!important;-webkit-hyphens:none!important;Margin:0;Margin-bottom:0;border-collapse:collapse!important;color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:300;hyphens:none!important;line-height:1.45;margin:0;margin-bottom:0;padding:0;text-align:left;white-space:no-wrap!important;word-break:keep-all!important;word-wrap:normal!important"><?php echo $serialNumber; ?></p>
                                                    <?php } ?>
                                                    </div>
                                                    
                                                        
                                                    
                                                      <div ap:edit="">
                                                    <p class="small-text-center" style="-moz-hyphens:none!important;-ms-hyphens:none!important;-webkit-hyphens:none!important;Margin:0;Margin-bottom:0;border-collapse:collapse!important;color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:300;hyphens:none!important;line-height:1.45;margin:0;margin-bottom:0;padding:0;text-align:left;white-space:no-wrap!important;word-break:keep-all!important;word-wrap:normal!important"><br>
                                                    Qty: <?= /* @escapeNotVerified */  $qty ?></p>
                                                </div>
    



                                                <table class="spacer" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                                                    <tbody>
                                                    <tr style="padding:0;text-align:left;vertical-align:top">
                                                        <td height="8px" style="-moz-hyphens:none;-webkit-hyphens:none;Margin:0;border-collapse:collapse!important;color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:8px;font-weight:lighter;hyphens:none;line-height:8px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-break:normal!important"></td>
                                                    </tr>
                                                    </tbody>
                                                </table>


                                                <table class="spacer" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                                                    <tbody>
                                                    <tr style="padding:0;text-align:left;vertical-align:top">
                                                        <td height="10px" style="-moz-hyphens:none;-webkit-hyphens:none;Margin:0;border-collapse:collapse!important;color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:10px;font-weight:lighter;hyphens:none;line-height:10px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-break:normal!important"></td>
                                                    </tr>
                                                    </tbody>
                                                </table>

                                                                                                   
                                           </th>
                                        </tr>
                                        </tbody>
                                    </table>
                                </th>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>

            <table align="center" class="container float-center" style="Margin:0 auto;background:#fff;border-collapse:collapse;border-spacing:0;float:none;margin:0 auto;padding:0;text-align:center;vertical-align:top;">
                <tbody>
                <tr style="padding:0;text-align:left;vertical-align:top">
                    <td style="-moz-hyphens:none;-webkit-hyphens:none;Margin:0;border-collapse:collapse!important;color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:lighter;hyphens:none;line-height:1.3;margin:0;padding:0;text-align:left;vertical-align:top;word-break:normal!important">
                        <table class="spacer" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                            <tbody>
                            <tr style="padding:0;text-align:left;vertical-align:top">
                                <td height="20px" style="-moz-hyphens:none;-webkit-hyphens:none;Margin:0;border-collapse:collapse!important;color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:lighter;hyphens:none;line-height:20px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-break:normal!important">
                                    <table class="spacer" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                                        <tbody>
                                            <tr style="padding:0;text-align:left;vertical-align:top">
                                                <td height="30px" style="-moz-hyphens:none;-webkit-hyphens:none;Margin:0;border-collapse:collapse!important;color:#535354;font-family:akkurat-light, Helvetica, Arial, Ubuntu, sans-serif;font-size:30px;font-weight:lighter;hyphens:none;line-height:30px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-break:normal!important"></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>
<?php } ?>