<?php 
$track = $block->getTrack();
$order = $block->getOrder();
$trackingUrl = $track ? $block->getTrackingLink($order, $track) : "";
?>

<p class="small-text-center" style="-moz-hyphens:none!important;-ms-hyphens:none!important;-webkit-hyphens:none!important;Margin:0;Margin-bottom:0;border-collapse:collapse!important;color:#ffffff;font-family:Helvetica, Arial, Ubuntu, sans-serif;font-size:16px;font-weight:lighter;hyphens:none!important;line-height:1;margin:0;margin-bottom:0;padding:0;text-align:center;white-space:no-wrap!important;word-break:keep-all!important;word-wrap:normal!important">
    <a style="-moz-hyphens:none!important;-ms-hyphens:none!important;-webkit-hyphens:none!important;hyphens:none!important;white-space:no-wrap!important;word-break:keep-all!important;word-wrap:normal!important; color:#ffffff!important; display: inline-block; background:#000000; border-radius: 30px;text-decoration: none;padding-top:13px;padding-bottom:13px;padding-left:40px;padding-right:40px;font-size:16px;" href="<?=$trackingUrl?>">Track your gift</a>
</p>