<?php
$giftMessage = '';
$order = $block->getOrder();
if($order->getGiftMessageId()) {
    
    $giftMessage = '<table class="row" style="border-collapse:collapse;border-spacing:0;display:table;padding:0;position:relative;text-align:left;vertical-align:top;width:100%">
    <tbody>
        <tr style="padding:0;text-align:left;vertical-align:top">
            <th class="small-12 large-6 columns first" style="Margin:0 auto;color:#000000;font-family:Helvetica, Arial, Ubuntu, sans-serif;font-size:16px;font-weight:lighter;line-height:1.3;margin:0 auto;padding:0;padding-bottom:0;padding-left:20px;padding-right:10px;text-align:left;width:280px">
            <table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                <tbody>
                    <tr style="padding:0;text-align:left;vertical-align:top">
                        <th style="Margin:0;color:#000000;font-family:Helvetica, Arial, Ubuntu, sans-serif;font-size:16px;font-weight:lighter;line-height:1.3;margin:0;padding:0;text-align:left">
                        <div ap:edit="">
                        <p style="-moz-hyphens:none!important;-ms-hyphens:none!important;-webkit-hyphens:none!important;Margin:0;Margin-bottom:0;border-collapse:collapse!important;color:#000000;font-family: Helvetica, Arial, Ubuntu, sans-serif;font-size:16px;font-weight:lighter;hyphens:none!important;line-height:1.45;margin:0;margin-bottom:0;padding:0;text-align:left;white-space:no-wrap!important;word-break:keep-all!important;word-wrap:normal!important"><strong style="-moz-hyphens:none!important;-ms-hyphens:none!important;-webkit-hyphens:none!important;hyphens:none!important;white-space:no-wrap!important;word-break:keep-all!important;word-wrap:normal!important">Gift message</strong></p>
                        </div>

                        <table class="spacer" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                            <tbody>
                                <tr style="padding:0;text-align:left;vertical-align:top">
                                    <td height="10px" style="-moz-hyphens:none;-webkit-hyphens:none;Margin:0;border-collapse:collapse!important;color:#000000;font-family: Helvetica, Arial, Ubuntu, sans-serif;font-size:10px;font-weight:lighter;hyphens:none;line-height:10px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-break:normal!important"></td>
                                </tr>
                            </tbody>
                        </table>
                        <div ap:edit="" style="-moz-hyphens:none!important;-ms-hyphens:none!important;-webkit-hyphens:none!important;Margin:0;Margin-bottom:0;border-collapse:collapse!important;color:#000000;font-family:Helvetica, Arial, Ubuntu, sans-serif;font-size:16px;font-weight:lighter;hyphens:none!important;line-height:1.45;margin:0;margin-bottom:0;padding:0;text-align:left;white-space:no-wrap!important;word-break:keep-all!important;word-wrap:normal!important">
                        <p style="margin-top:0;margin-bottom:0; border-collapse:collapse!important;color:#000000;font-family:Helvetica, Arial, Ubuntu, sans-serif;font-size:16px;font-weight:lighter;hyphens:none!important;line-height:1.45;">'. $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($order->getGiftMessageId())->getMessage() .'</p>
                        </div>
                        <table class="spacer" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                            <tbody>
                                <tr style="padding:0;text-align:left;vertical-align:top">
                                    <td height="25px" style="-moz-hyphens:none;-webkit-hyphens:none;Margin:0;border-collapse:collapse!important;color:#000000;font-family: Helvetica, Arial, Ubuntu, sans-serif;font-size:25px;font-weight:lighter;hyphens:none;line-height:25px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-break:normal!important"></td>
                                </tr>
                            </tbody>
                        </table>
                        </th>
                    </tr>
                </tbody>
            </table>
            </th>
        </tr>
    </tbody>
</table> ';
}
echo $giftMessage;