<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_shipment = $block->getShipment() ?>
<?php $_order    = $block->getOrder() ?>
<?php if ($_shipment && $_order): ?>
<p style="-moz-hyphens: none!important; -ms-hyphens: none!important; -webkit-hyphens: none!important; margin: 0; margin-bottom: 0; border-collapse: collapse!important; color: #535354; font-family: Helvetica,Arial,sans-serif; font-size: 16px; font-weight: lighter; hyphens: none!important; line-height: 1.45; padding: 0; text-align: left; white-space: no-wrap!important; word-break: keep-all!important; word-wrap: normal!important;">
    <strong>Items included in this shipment:</strong><br />
    <?php foreach ($_shipment->getAllItems() as $_item): ?>
        <?php if (!$_item->getOrderItem()->getParentItem()) : ?>
            <?php echo $_item->getName(); ?> - Qty: <?php echo intval($_item->getQty()); ?><br />
        <?php endif; ?>
    <?php endforeach; ?>
</p>
<br />
<?php endif; ?>
