<?php
namespace Mexbs\Tieredcoupon\Model;

use Magento\Framework\Model\AbstractModel;

class Autogenerated  extends AbstractModel
{
    /**
     * @return void
     */
    protected function _construct()
    {
        $this->_init('Mexbs\Tieredcoupon\Model\ResourceModel\Autogenerated');
    }
}