<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$_order = $block->getOrder();
if ($_order) {
    $_items = $_order->getAllItems();
    foreach ($_items as $_item) {
        if (!$_item->getParentItem()) {
            echo $block->getItemHtml($_item);
        }
    } ?>
    <table align="center" class="container float-center" style="margin:0 auto;background:#ffffff;border-collapse:collapse;border-spacing:0;float:none; margin:0 auto; padding:0; text-align:center; vertical-align:top; width:600px;">
        <tbody>
            <tr style="padding:0;text-align:left;vertical-align:top">
                <td bgcolor="white" style="-moz-hyphens:none;-webkit-hyphens:none;Margin:0;border-collapse:collapse!important;color:#535354;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:lighter;hyphens:none;line-height:1.3;margin:0;padding:0 20px;background-color:white;text-align:left;vertical-align:top;word-break:normal!important">
                    <table class="row" style="border-collapse:collapse;border-spacing:0;display:table;padding:0;position:relative;text-align:left;vertical-align:top;width:100%">
                        <tbody>
                        <tr style="padding:0;text-align:left;vertical-align:top">
                            <th class="small-12 large-6 columns first" style="Margin:0 auto;color:#535354;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:lighter;line-height:1.3;margin:0 auto;padding:0;padding-bottom:0;padding-left:20px;padding-right:10px;text-align:left;width:280px">
                                <table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                                    <tbody>
                                    <tr style="padding:0;text-align:left;vertical-align:top">
                                        <th style="Margin:0;color:#535354;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:lighter;line-height:1.3;margin:0;padding:0;text-align:left"></th>
                                    </tr>
                                    </tbody>
                                </table>
                            </th>
                            <th class="small-12 large-6 columns last" style="Margin:0 auto;color:#535354;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:lighter;line-height:1.3;margin:0 auto;padding:0;padding-bottom:0;padding-left:10px;padding-right:20px;text-align:left;width:280px">
                                <table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                                    <tbody>
                                    <tr style="padding:0;text-align:left;vertical-align:top">
                                        <th style="Margin:0;color:#535354;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:lighter;line-height:1.3;margin:0;padding:0;text-align:left">
                                            <table cellspacing="0" cellpadding="0" border="0" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                                                <tbody>
                                                    <?= $block->getChildHtml('order_totals') ?>
                                                </tbody>
                                            </table>
                                        </th>
                                    </tr>
                                    </tbody>
                                </table>
                            </th>
                        </tr>
                        </tbody>
                    </table>

                    <table class="spacer" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                        <tbody>
                        <tr style="padding:0;text-align:left;vertical-align:top">
                            <td height="25px" style="-moz-hyphens:none;-webkit-hyphens:none;Margin:0;border-collapse:collapse!important;color:#535354;font-family:Helvetica,Arial,sans-serif;font-size:25px;font-weight:lighter;hyphens:none;line-height:25px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-break:normal!important"></td>
                        </tr>
                        </tbody>
                    </table>

                    <table class="wrapper" align="center" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                        <tbody>
                        <tr style="padding:0;text-align:left;vertical-align:top">
                            <td class="wrapper-inner" style="-moz-hyphens:none;-webkit-hyphens:none;Margin:0;border-collapse:collapse!important;color:#535354;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:lighter;hyphens:none;line-height:1.3;margin:0;padding:0;text-align:left;vertical-align:top;word-break:normal!important">
                                <table class="row" style="border-collapse:collapse;border-spacing:0;display:table;padding:0;position:relative;text-align:left;vertical-align:top;width:100%">
                                    <tbody>
                                    <tr style="padding:0;text-align:left;vertical-align:top">
                                        <th class="small-12 large-12 columns first last" style="Margin:0 auto;color:#535354;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:lighter;line-height:1.3;margin:0 auto;padding:0;padding-bottom:0;padding-left:20px;padding-right:20px;text-align:left;width:580px">
                                            <table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                                                <tbody>
                                                <tr style="padding:0;text-align:left;vertical-align:top">
                                                    <th style="Margin:0;color:#535354;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:lighter;line-height:1.3;margin:0;padding:0;text-align:left">
                                                        <p width="100%" class="hr-custom" style="-moz-hyphens:none!important;-ms-hyphens:none!important;-webkit-hyphens:none!important;Margin:0;Margin-bottom:0;border-collapse:collapse!important;border-top:1px solid #d0d0d0;color:#fff;font-family:Helvetica,Arial,sans-serif;font-size:1px;font-weight:lighter;height:1px!important;hyphens:none!important;line-height:1.45;margin:0;margin-bottom:0!important;min-height:1px!important;padding:0;padding-bottom:0!important;text-align:left;white-space:no-wrap!important;width:100%;word-break:keep-all!important;word-wrap:normal!important"><span style="-moz-hyphens:none!important;-ms-hyphens:none!important;-webkit-hyphens:none!important;color:#fff;font-size:1px;hyphens:none!important;visibility:hidden!important;white-space:no-wrap!important;word-break:keep-all!important;word-wrap:normal!important"><font color="white">&nbsp;</font></span></p>
                                                    </th>
                                                    <th class="expander" style="Margin:0;color:#535354;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:lighter;line-height:1.3;margin:0;padding:0!important;text-align:left;visibility:hidden;width:0"></th>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </th>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        </tbody>
                    </table>

                    <table class="spacer" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                        <tbody>
                            <tr style="padding:0;text-align:left;vertical-align:top">
                                <td height="20px" style="-moz-hyphens:none;-webkit-hyphens:none;Margin:0;border-collapse:collapse!important;color:#535354;font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:lighter;hyphens:none;line-height:20px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-break:normal!important"></td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
<?php } ?>
