<?php
/**
 * Created by:  Milan Simek
 * Company:     Plugin Company
 *
 * LICENSE: http://plugin.company/docs/magento-extensions/magento-extension-license-agreement
 *
 * YOU WILL ALSO FIND A PDF COPY OF THE LICENSE IN THE DOWNLOADED ZIP FILE
 *
 * FOR QUESTIONS AND SUPPORT
 * PLEASE DON'T HESITATE TO CONTACT US AT:
 *
 * SUPPORT@PLUGIN.COMPANY
 */
?>
<div id="sales-rule-form-tab-coupons">
    <div class="messages pc-coupon-import-message" style="display:none;">
        <div class="message message-info info">
            <?= __("To enable bulk importing coupon codes, please select 'Specific Coupon' and check the 'Use Auto Generation' checkbox in the Rule Information tab.") ?>
        </div>
    </div>
    <?php echo $block->getChildHtml('plugincompany_import_coupons') ?>
    <?php echo $block->getChildHtml('promo_quote_edit_tab_coupons_form') ?>
    <?php echo $block->getChildHtml('promo_quote_edit_tab_coupons_grid') ?>
</div>
