<div class="value-props">
    <ul class="value-props-ul">
        <li class="value-props-list u-hideMobile"> 
            <img src='<?php echo $block->getViewFileUrl('Aheadworks_OneStepCheckout::images/truck.png'); ?>' alt="shipping-icon">
            <span class="icon-text">Free<br> shipping</span></li>
        <li class="value-props-list">
            <img src='<?php echo $block->getViewFileUrl('Aheadworks_OneStepCheckout::images/calender.png'); ?>' alt="calender-icon">    
            <span class="icon-text">Free 30-day <br>returns</span>
        </li>
        <li class="value-props-list u-hideMobile">
            <img src='<?php echo $block->getViewFileUrl('Aheadworks_OneStepCheckout::images/years.png'); ?>' alt="calender-icon">
            <span class="icon-text">2-year <br>warranty</span>
        </li>
    </ul>
</div>