<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Resetpassword $block */

?>

<p class="welcome-text">Create a new password.</p>

<form action="<?= $block->escapeUrl($block->getUrl('*/*/resetpasswordpost', ['_query' => ['token' => $block->getResetPasswordLinkToken(), 'email' => $block->getResetPasswordLinkEmail()]])) ?>"
      method="post"
      <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?>
      id="form-validate"
      class="form password reset"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" data-mage-init='{"awOscFloatLabel": {}}'>
        <div class="field password required fl-label fl-label-state" data-mage-init='{"passwordStrengthIndicator": {}}'>
            <label class="label" for="password"><span><?= $block->escapeHtml(__('Create new password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password"
                       data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                       data-validate="{required:true, passwordStrength:true}"
                       autocomplete="off">
                <span class="tooltip">
                    <span class="tooltip-content">
                        8 character min.<br />
                        1 lowercase letter<br />
                        1 uppercase letter<br />
                        1 number<br />
                        1 special character<br />
                    </span>
                </span>
            </div>
            <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                <div id="password-strength-meter" class="password-strength-meter">
                    <?= $block->escapeHtml(__('Password Strength')) ?>:
                    <span id="password-strength-meter-label" data-role="password-strength-meter-label"></span>
                </div>
            </div>
        </div>
        <div class="field confirmation required fl-label fl-label-state">
            <label class="label" for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm new password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password-confirmation" data-validate="{required:true,equalTo:'#password'}" autocomplete="off">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Reset password')) ?></span></button>
        </div>
    </div>
</form>

<script type="text/x-magento-init">
    {"*": {"Vonnda_TealiumTags/js/login":{}}}
</script>

<script>
    require([
        "jquery"
    ], function($){
        $('input#password').on('blur', function(){
            $(this).closest('.field').find('#password-strength-meter').show();
        });
    });
</script>
