<?php
namespace Mexbs\Tieredcoupon\Controller\Adminhtml\Coupon;

class AutogeneratedMassDelete extends \Mexbs\Tieredcoupon\Controller\Adminhtml\Coupon\Tieredcoupon
{
    protected $tieredCouponFactory;
    protected $autogeneratedCollectionFactory;

    public function __construct(
        \Mexbs\Tieredcoupon\Model\TieredcouponFactory $tieredCouponFactory,
        \Mexbs\Tieredcoupon\Model\ResourceModel\Autogenerated\CollectionFactory $autogeneratedCollectionFactory,
        \Magento\Backend\App\Action\Context $context
    )
    {
        $this->tieredCouponFactory = $tieredCouponFactory;
        $this->autogeneratedCollectionFactory = $autogeneratedCollectionFactory;
        parent::__construct($context);
    }

    public function execute()
    {
        $id = $this->getRequest()->getParam('id');
        if (!$id) {
            $this->_forward('noroute');
        }

        $tieredCoupon = $this->tieredCouponFactory->create()->load($id);
        if (!$tieredCoupon->getId()) {
            $this->_forward('noroute');
        }

        $codesIds = $this->getRequest()->getParam('ids');

        if (is_array($codesIds)) {
            $couponsCollection = $this->autogeneratedCollectionFactory
                ->create()->addFieldToFilter(
                'tieredcoupon_autogenerated_id',
                ['in' => $codesIds]
            );

            foreach ($couponsCollection as $coupon) {
                $coupon->delete();
            }
        }
    }
}
