<?php
namespace Mexbs\Tieredcoupon\Controller\Adminhtml\Coupon;

class AutogeneratedCouponsGrid extends \Mexbs\Tieredcoupon\Controller\Adminhtml\Coupon\Tieredcoupon
{
    public function execute()
    {
        $this->_initTieredcoupon();
        $this->_view->loadLayout();
        $this->_view->getPage()->getConfig()->getTitle()->prepend(__('Autogenerated Coupons'));
        $this->_view->renderLayout();
    }
}
