<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var $block \Magento\Sales\Block\Order\Info */

// @codingStandardsIgnoreFile
?>
<?php $order = $block->getOrder() ?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?php echo $block->escapeHtml(__('Order information')) ?></strong>
    </div>
    <div class="block-content">
    <?php if (!$order->getIsVirtual()): ?>
        <div class="box box-order-shipping-address">
            <strong class="box-title no-margin">
                <?php if($order->getGiftOrder()){ ?> 
                    <span><?php echo $block->escapeHtml(__('Recipient address')) ?></span>
                <?php } else { ?> 
                    <span><?php echo $block->escapeHtml(__('Shipping address')) ?></span>
                <?php } ?>
            </strong>
            <div class="box-content">
                <address><?php /* @noEscape */ echo $block->getFormattedAddress($order->getShippingAddress()); ?></address>
                <?= $order->getGiftOrder() ? $order->getShippingAddress()->getGiftRecipientEmail() : "" ?>
            </div>
        </div>

        <div class="box box-order-shipping-method">
            <strong class="box-title no-margin">
                <span><?php echo $block->escapeHtml(__('Shipping method')) ?></span>
            </strong>
            <div class="box-content">
            <?php if ($order->getShippingDescription()): ?>
                <!-- Translate the  -->
                <?php echo __($block->escapeHtml($order->getShippingDescription())) ?>
            <?php else: ?>
                <?php echo $block->escapeHtml(__('No shipping information available')) ?>
            <?php endif; ?>
            <?php echo $block->getChildHtml('aw_delivery_date') ?>
            </div>

            <div class="box box-order-billing-method">
                <strong class="box-title no-margin">
                    <span><?php echo $block->escapeHtml(__('Payment')) ?></span>
                </strong>
                <div class="box-content">
                    <?php echo $block->getPaymentInfoHtml() ?>
                </div>
            </div>
        </div>
    <?php endif; ?>

        <div class="box box-order-billing-address">
            <strong class="box-title no-margin">
                <span><?php echo $block->escapeHtml(__('Billing address')) ?></span>
            </strong>
            <div class="box-content">
                <address><?php /* @noEscape */ echo $block->getFormattedAddress($order->getBillingAddress()); ?></address>
            </div>
        </div>
    </div>
</div>
