<?php
namespace Mexbs\Tieredcoupon\Setup;

use Magento\Framework\Setup\UpgradeSchemaInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\SchemaSetupInterface;
use Magento\Framework\DB\Adapter\AdapterInterface;

class UpgradeSchema implements UpgradeSchemaInterface
{
    public function upgrade(SchemaSetupInterface $setup, ModuleContextInterface $context)
    {
        $installer = $setup;
        $installer->startSetup();
        if (version_compare($context->getVersion(), '1.0.4', '<')) {
            $setup->getConnection()->addIndex(
                $installer->getTable('mexbs_tieredcoupon'),
                $installer->getIdxName($installer->getTable('mexbs_tieredcoupon'), ['code'], AdapterInterface::INDEX_TYPE_UNIQUE),
                ['code'],
                AdapterInterface::INDEX_TYPE_UNIQUE
            );
        }


        if (version_compare($context->getVersion(), '1.1.0', '<')) {
            /**
             * Create table 'mexbs_tieredcoupon_autogenerated'
             */
            $table = $installer->getConnection()->newTable(
                $installer->getTable('mexbs_tieredcoupon_autogenerated')
            )->addColumn(
                    'tieredcoupon_autogenerated_id',
                    \Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
                    null,
                    ['identity' => true, 'unsigned' => true, 'nullable' => false, 'primary' => true],
                    'Autogenerated Tieredcoupon Id'
            )->addColumn(
                'tieredcoupon_id',
                \Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
                null,
                ['unsigned' => true, 'nullable' => false],
                'Tieredcoupon Id'
            )->addColumn(
                'code',
                \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                '255',
                [],
                'Code'
            )->addColumn(
                'created_at',
                \Magento\Framework\DB\Ddl\Table::TYPE_TIMESTAMP,
                null,
                ['nullable' => false, 'default' => \Magento\Framework\DB\Ddl\Table::TIMESTAMP_INIT],
                'Created At'
            )->addForeignKey(
                $installer->getFkName('mexbs_tieredcoupon_autogenerated', 'tieredcoupon_id', 'mexbs_tieredcoupon', 'tieredcoupon_id'),
                'tieredcoupon_id',
                $installer->getTable('mexbs_tieredcoupon'),
                'tieredcoupon_id',
                \Magento\Framework\DB\Ddl\Table::ACTION_CASCADE
            )->addIndex(
                $installer->getIdxName('mexbs_tieredcoupon', ['code']),
                ['code']
            )->setComment(
                'Autogenerated Tiered Coupons'
            );

            $installer->getConnection()->createTable($table);
        }

        if (version_compare($context->getVersion(), '1.1.1', '<')) {
            $setup->getConnection()->addColumn(
                $installer->getTable('mexbs_tieredcoupon_autogenerated'),
                'times_used',
                [
                    'type' => \Magento\Framework\DB\Ddl\Table::TYPE_SMALLINT,
                    'length' => '6',
                    'nullable' => false,
                    'default' => 0,
                    'comment' => 'How many times the coupon code was used'
                ]
            );
        }

        $installer->endSetup();
    }
}
