<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<?php foreach ($block->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?= $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else:?>
        <tr class="<?= /* @escapeNotVerified */ $_code ?>">
            <th colspan="2" class="mark" scope="row" <?php echo ($block->escapeHtml($_total->getLabel()) == 'Discount' ? ' style="width:50%;padding:5px 15px;background-color:#cfe9db;border-radius: 4px 0 0 4px;font-weight:300;"' : 'style="width:50%;padding:5px 15px;font-weight:300; color:#000; font-size:16px;"') ?>>
                <?php if(strip_tags($_total->getLabel()) == 'Order total'): ?>
                    <strong>Return total</strong>
                <?php else:?>
                    <?= $block->escapeHtml($_total->getLabel()) ?>
                <?php endif?>
            </th>
            <td <?= /* @escapeNotVerified */ $block->getValueProperties() ?> data-th="<?= $block->escapeHtml($_total->getLabel()) ?>" <?php echo ($block->escapeHtml($_total->getLabel()) == 'Discount' ? ' style="width:50%;padding:5px 15px;background-color:#cfe9db;border-radius: 0 4px 4px 0;font-weight:300;text-align:right;font-family:Helvetica,Arial,sans-serif; color:#000; font-size:16px"' : 'style="width:50%;padding:5px 15px;font-weight:300;text-align:right;font-family:Helvetica,Arial,sans-serif; color:#000; font-size:16px"') ?>>
                <?php if($_total->getLabel() == 'Order total'): ?>
                    <strong><?= /* @escapeNotVerified */ $block->formatValue($_total) ?></strong>
                <?php else:?>
                    <?= /* @escapeNotVerified */ $block->formatValue($_total) ?>
                <?php endif?>
            </td>
        </tr>
        <tr>
            <td class="empty" style="height: 12px;width: 100%;" colspan="3"></td>
        </tr>
    <?php endif?>
<?php endforeach?>
