<?php 
    $order = $block->getOrder();
?>
<table align="center" class="container float-center" style="Margin:0 auto;background:#fff;border-collapse:collapse;border-spacing:0;float:none;margin:0 auto;padding:0;text-align:center;vertical-align:top;width:600px">
    <tbody>
        <tr style="padding:0;text-align:left;vertical-align:top">
            <td style="-moz-hyphens:none;-webkit-hyphens:none;Margin:0;border-collapse:collapse!important;color:#535354;font-family:Helvetica, Arial, Ubuntu, sans-serif;font-size:16px;font-weight:lighter;hyphens:none;line-height:1.3;margin:0;padding:0;text-align:left;vertical-align:top;word-break:normal!important">
            <table class="row" style="border-collapse:collapse;border-spacing:0;display:table;padding:0;position:relative;text-align:left;vertical-align:top;width:100%">
                <tbody>
                    <tr style="padding:0;text-align:left;vertical-align:top">
                        <th class="small-12 columns first" style="Margin:0 auto;color:#535354;font-family:Helvetica, Arial, Ubuntu, sans-serif;font-size:16px;font-weight:lighter;line-height:1.3;margin:0 auto;padding:0;padding-bottom:0;padding-left:20px;padding-right:20px;text-align:left;width:100%">
                            <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#cfe9db;background-color:#cfe9db;width:100%;border-radius:4px;">
                                <tbody>
                                    <tr>
                                        <td style="direction:ltr;font-size:0px;padding-left:15px;padding-right:15px;text-align:center;">
                                            <div
                                                class="mj-column-per-100 outlook-group-fix"
                                                style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
                                            >
                                                <table
                                                    border="0"
                                                    cellpadding="0"
                                                    cellspacing="0"
                                                    role="presentation"
                                                    width="100%"
                                                >
                                                    <tbody>
                                                        <tr>
                                                            <td style="vertical-align:top;padding-top:0;padding-bottom:0;">
                                                                <table
                                                                    border="0"
                                                                    cellpadding="0"
                                                                    cellspacing="0"
                                                                    role="presentation"
                                                                    style=""
                                                                    width="100%"
                                                                >
                                                                    <tbody>
                                                                        <tr>
                                                                            <td align="left" style="font-size:0px;padding:10px 25px;padding-top:0;padding-right:5px;padding-bottom:0;padding-left:5px;word-break:break-word;">
                                                                                <div style="font-family:Helvetica, Arial, Ubuntu, sans-serif;font-size:16px;font-weight:300;letter-spacing:0px;line-height:1.25;text-align:left;color:#000000;">
                                                                                    <?php echo $block->getShippingWarningMessage($order); ?>
                                                                                </div>
                                                                            </td>
                                                                        </tr>
                                                                    </tbody>
                                                                </table>
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>

                        </th>
                    </tr>
                </tbody>
            </table>

            <table class="spacer" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
                <tbody>
                    <tr style="padding:0;text-align:left;vertical-align:top">
                        <td height="15px" style="-moz-hyphens:none;-webkit-hyphens:none;Margin:0;border-collapse:collapse!important;color:#535354;font-family:akkurat-light, Helvetica, Arial, Ubuntu, sans-serif;font-size:15px;font-weight:lighter;hyphens:none;line-height:15px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-break:normal!important"></td>
                    </tr>
                </tbody>
            </table>
            </td>
        </tr>
    </tbody>
</table>