<?php
/** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */
?>
<?php $parentItem = $block->getItem() ?>
<?php $options = $parentItem->getProductOptionByCode('bundle_options'); ?>
<div class="u-epsilon item-options">
<?php foreach ($options as $option): ?>
    <div>
        <span class="row-label"><?php /* @escapeNotVerified */ echo trim($option['label']) ?>:</span>
        <span class="row-value">
            <?php foreach ($option['value'] as $product): ?>
                <span class="tooltip content row-value"><?php echo trim($block->escapeHtml($product['title'])) ?> x <?php echo trim($block->escapeHtml($product['qty'])) ?></span>
            <?php endforeach; ?>
        </span>
    </div>
<?php endforeach; ?>
</div>
<?php if ($options = $block->getItemOptions()): ?>
    <div class="item-options">
        <?php foreach ($options as $option) : ?>
            <div>
                <span class="row-label"><?php echo trim($block->escapeHtml($option['label'])); ?>:</span>
                <?php if (!$block->getPrintStatus()): ?>
                    <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                    <span<?php if (isset($formatedOptionValue['full_view'])): ?> class="tooltip wrapper column-right row-value"<?php endif; ?>>
                        <?php /* @escapeNotVerified */ echo trim($formatedOptionValue['value']) ?>
                        <?php if (isset($formatedOptionValue['full_view'])): ?>
                            <div class="tooltip content">
                                <div class="item options">
                                    <span class="row-label"><?php echo trim($block->escapeHtml($option['label'])); ?>:</span>
                                    <span class="row-value"><?php /* @escapeNotVerified */ echo trim($formatedOptionValue['full_view']) ?></span>
                                </div>
                            </div>
                        <?php endif; ?>
                    </span>
                <?php else: ?>
                    <span class="row-value"><?php echo trim($block->escapeHtml((isset($option['print_value']) ? $option['print_value'] : $option['value']))); ?></span>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
