<?php if ($options = $block->getItemOptions()): ?>
    <div class="u-epsilon item-options">
        <?php foreach ($options as $option) : ?>
            <div>
                <span class="row-label"><?php echo trim($block->escapeHtml($option['label'])) ?>:</span>
                <?php if (!$block->getPrintStatus()): ?>
                    <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                    <span class="row-value">
                        <?php if (isset($formatedOptionValue['full_view'])): ?>
                            <?php /* @escapeNotVerified */ echo trim($formatedOptionValue['full_view']) ?>
                        <?php else: ?>
                            <?php /* @escapeNotVerified */ echo trim($formatedOptionValue['value']) ?>
                        <?php endif; ?>
                    </span>
                <?php else: ?>
                    <span class="row-value">
                        <?php echo nl2br($block->escapeHtml((isset($option['print_value']) ? $option['print_value'] : $option['value']))) ?>
                    </span>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
