<?php
/** @var $block \Magento\Downloadable\Block\Sales\Order\Item\Renderer\Downloadable */
?>
<?php $item = $block->getItem() ?>
<?php if ($options = $block->getItemOptions()): ?>
    <div class="u-epsilon item-options links">
        <?php foreach ($options as $option) : ?>
            <div>
                <span class="row-label"><?php echo trim($block->escapeHtml($option['label'])) ?>:</span>
                <?php if (!$block->getPrintStatus()): ?>
                    <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                    <span class="row-value" <?php if (isset($formatedOptionValue['full_view'])): ?> class="tooltip wrapper"<?php endif; ?>>
                        <?php /* @escapeNotVerified */ echo trim($formatedOptionValue['value']) ?>
                        <?php if (isset($formatedOptionValue['full_view'])): ?>
                            <div class="tooltip content">
                                <div class="item options">
                                    <span class="row-label"><?php echo trim($block->escapeHtml($option['label'])) ?>:</span>
                                    <span class="row-value"><?php /* @escapeNotVerified */ echo trim($formatedOptionValue['full_view']) ?></span>
                                </div>
                            </div>
                        <?php endif; ?>
                    </span>
                <?php else: ?>
                    <span class="row-value">
                        <?php echo nl2br($block->escapeHtml((isset($option['print_value']) ? $option['print_value'] : $option['value']))) ?>
                    </span>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<?php /* downloadable */ ?>
<?php if ($links = $block->getLinks()): ?>
    <div class="item-options links">
        <span class="row-label"><?php /* @escapeNotVerified */ echo $block->getLinksTitle() ?>:</span>
        <?php foreach ($links->getPurchasedItems() as $link): ?>
            <span class="tooltip content row-value"><?php echo trim($block->escapeHtml($link->getLinkTitle())); ?></span>
        <?php endforeach; ?>
    </div>
<?php endif; ?>

