<?php

namespace Mexbs\Tieredcoupon\Block\Adminhtml\Coupon\Edit\Tab\Coupons;


class Grid extends \Magento\Backend\Block\Widget\Grid\Extended
{
    protected $_coreRegistry = null;
    protected $autogeneratedCouponsCollection;


    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Backend\Helper\Data $backendHelper,
        \Mexbs\Tieredcoupon\Model\ResourceModel\Autogenerated\CollectionFactory $autogeneratedCouponsCollection,
        \Magento\Framework\Registry $coreRegistry,
        array $data = []
    ) {
        $this->_coreRegistry = $coreRegistry;
        $this->autogeneratedCouponsCollection = $autogeneratedCouponsCollection;
        parent::__construct($context, $backendHelper, $data);
    }


    protected function _construct()
    {
        parent::_construct();
        $this->setId('couponCodesGrid');
        $this->setUseAjax(true);
    }

    protected function _prepareCollection()
    {
        $tieredCoupon = $this->_coreRegistry->registry(\Mexbs\Tieredcoupon\Model\RegistryConstants::CURRENT_COUPON);

        /**
         * @var \Magento\SalesRule\Model\ResourceModel\Coupon\Collection $collection
         */
        $collection = $this->autogeneratedCouponsCollection->create();
        $collection->addFieldToFilter("tieredcoupon_id", $tieredCoupon->getId());

        $this->setCollection($collection);

        return parent::_prepareCollection();
    }

    protected function _prepareColumns()
    {
        $this->addColumn('code', ['header' => __('Coupon Code'), 'index' => 'code']);

        $this->addColumn(
            'created_at',
            [
                'header' => __('Created'),
                'index' => 'created_at',
                'type' => 'datetime',
                'align' => 'center',
                'width' => '160'
            ]
        );

        $this->addColumn(
            'times_used',
            ['header' => __('Times Used'), 'index' => 'times_used', 'width' => '50', 'type' => 'number']
        );

        return parent::_prepareColumns();
    }


    protected function _prepareMassaction()
    {
        $this->setMassactionIdField('tieredcoupon_autogenerated_id');
        $this->getMassactionBlock()->setFormFieldName('ids');
        $this->getMassactionBlock()->setUseAjax(true);
        $this->getMassactionBlock()->setHideFormElement(true);

        $this->getMassactionBlock()->addItem(
            'delete',
            [
                'label' => __('Delete'),
                'url' => $this->getUrl('tieredcoupon/coupon/autogeneratedMassDelete', ['_current' => true]),
                'confirm' => __('Are you sure you want to delete the selected coupon(s)?'),
                'complete' => 'refreshCouponCodesGrid'
            ]
        );

        return $this;
    }

    public function getGridUrl()
    {
        return $this->getUrl('tieredcoupon/coupon/autogeneratedCouponsGrid', ['_current' => true]);
    }
}
