<?php
namespace Mexbs\Tieredcoupon\Model\ResourceModel;

use Magento\Framework\Model\ResourceModel\Db\AbstractDb;

class Autogenerated extends AbstractDb
{
    protected function _construct()
    {
        $this->_init('mexbs_tieredcoupon_autogenerated', 'tieredcoupon_autogenerated_id');
    }
}