<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Framework\View\Element\Template */

/** @var $block \Magento\Framework\View\Element\Template */
$_gridPopupBlock = $block->getChildBlock('catalog.product.group.grid.popup.container')->getChildBlock('grid');
$_gridPopupBlock->setRowClickCallback('function(){}');
?>
<br>
<div class="fieldset-wrapper-title"><span class="title">Tier Product Chooser</span></div>
<script>
    window.subscriptionPlanProducts = <?php echo $block->getSubscriptionProductsForPlanJSON(); ?>
</script><br>
<div id="grouped-product-container" data-mage-init='{"Vonnda_Subscription/js/subscription-plan-product-chooser":{"gridPopup":"[data-grid-id=<?= /* @escapeNotVerified */ $_gridPopupBlock->getId() ?>]"}}'>
    <div data-role="add-product-dialog" class="no-display">
        <?= $block->getChildBlock('catalog.product.group.grid.popup.container')->getChildHtml('grid') ?>
    </div>
    <button type="button" data-role="add-product">Configure Products</button>

</div>
<br>
<div class="product-chooser__container">
    <table class="data-grid">
        <tr class="product-chooser__heading-row">
            <th class="data-grid-th">Name</th>
            <th class="data-grid-th">Sku</th>
            <th class="data-grid-th">Quantity</th>
            <th class="data-grid-th">Price Override</th>
        </tr>
        <tr class="product-chooser__item data-row">
        </tr>
    </table>
</div>