<?php 
    $subscriptionPlan = $block->getSubscriptionPlan();
    if($subscriptionPlan){
        ?><h1>Tier</h1><?php
        ?>
        <div class="fieldset-wrapper-title"><span class="title">Tier Info</span></div>
        <table class="admin__table-secondary">
            <tbody>
            <tr>
                <th>Created:</th>
                <td><?php echo $subscriptionPlan->getCreatedAt();?></td>
            </tr>
            <tr>
                <th>Last Modified:</th>
                <td><?php echo $subscriptionPlan->getUpdatedAt();?></td>
            </tr>
            </tbody>
        </table>

        <?php
    } else {
        ?><h1>Add New Tier</h1><?php
    }
?>